-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: May 24, 2024 at 06:42 AM
-- Server version: 8.0.31
-- PHP Version: 8.1.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `httnmagzine_httn_magazine`
--

-- --------------------------------------------------------

--
-- Table structure for table `magcontent`
--

DROP TABLE IF EXISTS `magcontent`;
CREATE TABLE IF NOT EXISTS `magcontent` (
  `id` int NOT NULL AUTO_INCREMENT,
  `productId` int DEFAULT NULL,
  `product_category` varchar(255) DEFAULT NULL,
  `language` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `content_name` varchar(255) DEFAULT NULL,
  `content_description` text,
  `content_url1` varchar(255) DEFAULT NULL,
  `content_url2` varchar(255) DEFAULT NULL,
  `content_url3` varchar(255) DEFAULT NULL,
  `content_url4` varchar(255) DEFAULT NULL,
  `content_url5` varchar(255) DEFAULT NULL,
  `content_url6` varchar(255) DEFAULT NULL,
  `content_url7` varchar(255) DEFAULT NULL,
  `content_url8` varchar(255) DEFAULT NULL,
  `content_url9` varchar(255) DEFAULT NULL,
  `content_text` text,
  `thumbnail` varchar(255) DEFAULT NULL,
  `content_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `content_image1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `content_image2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `key_words` varchar(255) DEFAULT NULL,
  `content_date` date DEFAULT NULL,
  `timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=73 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `magcontent`
--

INSERT INTO `magcontent` (`id`, `productId`, `product_category`, `language`, `content_name`, `content_description`, `content_url1`, `content_url2`, `content_url3`, `content_url4`, `content_url5`, `content_url6`, `content_url7`, `content_url8`, `content_url9`, `content_text`, `thumbnail`, `content_image`, `content_image1`, `content_image2`, `key_words`, `content_date`, `timestamp`) VALUES
(1, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(2, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(3, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(4, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(5, 4, 'Program videos', 'Chenoua', 'Healing Everywhere', 'Take healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>Take healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'healing, grace, God, Healing Streams, Rhapsody', '2024-05-23', '2024-05-21 14:41:28'),
(6, 13, 'Healthy Living Compendium Book', 'Igbo', 'Healing to the nations of the world', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>Healing Everywhere To The Galaxies</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God, Nations, Healing, Church', '2024-05-22', '2024-05-21 14:41:28'),
(7, 12, 'Global Health Blog', 'Ormuri', 'Healing Everywhere', 'Healing To The Nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.phphttp://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>Spread healing to the nations of the world</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Greatness, God', '2024-05-21', '2024-05-21 14:41:28'),
(8, 14, 'Global Health Blog', 'Ruund (Angola)', 'Healing To The Nations', 'Healing To The Nations Of The World', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', '<p>Spread healing everywhere, till the ends of the earth.</p>', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'God, Health, Wellness, Sound Health', '2024-05-22', '0000-00-00 00:00:00'),
(9, 14, 'Global Health Blog', 'Ruund (Angola)', 'Healing To The Nations', 'Healing To The Nations Of The World', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', '<p>Spread healing everywhere, till the ends of the earth.</p>', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'God, Health, Wellness, Sound Health', '2024-05-22', '0000-00-00 00:00:00'),
(10, 6, 'Outreach videos', 'Baagi', 'Healing Everywhere', 'Healing To The Nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.phphttp://localhost/RuangAdmin-master/form_basics.phphttp://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>Healing To The Nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God, honor, majesty', '2024-05-22', '2024-05-21 14:41:28'),
(11, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(12, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(13, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(14, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(15, 7, 'Program videos', 'Warduji', 'Healing Everywhere', 'Take healing to the nations of the world', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'Take Healing Everywhere', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'God health wellness', '2024-05-21', '2024-05-21 14:41:28'),
(16, 7, 'Program videos', 'Warduji', 'Healing Everywhere', 'Take healing to the nations of the world', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'Take Healing Everywhere', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'God health wellness', '2024-05-21', '2024-05-21 14:41:28'),
(17, 7, 'Program videos', 'Warduji', 'Healing Everywhere', 'Take healing to the nations of the world', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'Take Healing Everywhere', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'God health wellness', '2024-05-21', '2024-05-21 14:41:28'),
(18, 14, 'Global Health Blog', 'Ruund (Angola)', 'Healing To The Nations', 'Healing To The Nations Of The World', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', '<p>Spread healing everywhere, till the ends of the earth.</p>', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'God, Health, Wellness, Sound Health', '2024-05-22', '0000-00-00 00:00:00'),
(19, 14, 'Global Health Blog', 'Ruund (Angola)', 'Healing To The Nations', 'Healing To The Nations Of The World', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', '<p>Spread healing everywhere, till the ends of the earth.</p>', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'God, Health, Wellness, Sound Health', '2024-05-22', '0000-00-00 00:00:00'),
(20, 14, 'Global Health Blog', 'Ruund (Angola)', 'Healing To The Nations', 'Healing To The Nations Of The World', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', '<p>Spread healing everywhere, till the ends of the earth.</p>', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'God, Health, Wellness, Sound Health', '2024-05-22', '0000-00-00 00:00:00'),
(21, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(22, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(23, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(24, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(25, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(48, 9, 'Faith Proclamations Book', 'English language', 'Healing To The Nations Of The World', 'Healing To The Nations Of The World And The Galaxies', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Healing To The Nations Of The World And Galaxies', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God, Healing, Nations', '2024-05-22', '2024-05-21 14:41:28'),
(26, 0, '', 'Khasi (Afghan)', 'Healing To The Nations', 'Take healing to the nations of the world and spread healing everywhere.', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Take healing to the nations of the world and spread it everywhere.', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God, hope and salvation', '2024-05-22', '2024-05-21 14:41:28'),
(27, 12, '', 'Tamazight, Tidikelt', 'Healing Everywhere', 'Take healing to the nations of the world', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Take healing to the nations of the world and the galaxies', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God, Man, Sandra', '2024-05-22', '2024-05-21 14:41:28'),
(28, 12, '', 'Tamazight, Tidikelt', 'Healing Everywhere', 'Take healing to the nations of the world', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Take healing to the nations of the world and the galaxies', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God, Man, Sandra', '2024-05-22', '2024-05-21 14:41:28'),
(29, 12, '', 'Tamazight, Tidikelt', 'Healing Everywhere', 'Take healing to the nations of the world', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Take healing to the nations of the world and the galaxies', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God, Man, Sandra', '2024-05-22', '2024-05-21 14:41:28'),
(30, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(31, 4, 'Miracle Videos', 'Bathari', 'Healing To The Nations', 'Take Healing To The Nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Take God\'s Divine Presence To The World', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God, Healing, Health', '2024-05-22', '2024-05-21 14:41:28'),
(32, 5, 'Partnership videos', 'Brahui', 'Healing To The Nations', 'Take Healing To The Nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Take God\'s Divine Presence To The World', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God, Healing, Health', '2024-05-22', '2024-05-21 14:41:28'),
(33, 9, 'Faith Proclamations Book', 'TEKEEBOO', 'Healing Everywhere', 'Healing Everywhere To The Nations Of The World', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.phphttp://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Take Healing To The Nations Of The World', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God, Help', '2024-05-22', '2024-05-21 14:41:28'),
(34, 13, 'Healthy Living Compendium Book', 'Hikwanyama', 'Healing Everwhere', 'Take Healing To The Nations Of The World', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Spread Healing Everywhere', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Humanity', '2024-05-29', '2024-05-21 14:41:28'),
(35, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(36, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(37, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(42, 1, 'Faith Proclamations Book', '', 'Healing Everywhere', 'Healing to the nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', '<p>healing to the nations</p>', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Healing Streams', '2024-05-16', '2024-05-21 14:41:28'),
(49, 9, 'Faith Proclamations Book', 'English language', 'Healing To The Nations Of The World', 'Healing To The Nations Of The World And The Galaxies', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Healing To The Nations Of The World And Galaxies', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God, Healing, Nations', '2024-05-22', '2024-05-21 14:41:28'),
(47, 14, 'Global Health Blog', 'Ruund (Angola)', 'Healing To The Nations', 'Healing To The Nations Of The World', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', '<p>Spread healing everywhere, till the ends of the earth.</p>', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'God, Health, Wellness, Sound Health', '2024-05-22', '0000-00-00 00:00:00'),
(50, 10, 'Testimony Text', 'English language', 'Healing To The Nations', 'Spread healing to the nations of the world', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Take healing to the nations of the world', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God, Health, Nations', '2024-05-23', '2024-05-22 06:47:57'),
(65, 14, 'Platform Features', '', 'Healing Everywhere', 'Healing Everywhere', 'http://localhost/fresh/index.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Healing Everywhere', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Is Good', '2024-05-23', '2024-05-22 13:32:14'),
(64, 13, 'Healthy Living Compendium Book', 'English language', 'Healing Everywhere', 'Healing Everywhere', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Healing everywhere', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.phphttp://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Man, Men, Everywhere', '2024-05-30', '2024-05-22 13:28:40'),
(58, 10, 'Testimony Text', '', 'Healing Everywhere', 'Healing Everywhere', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Healing Everywhere', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Man Health', '2024-05-23', '2024-05-22 13:00:08'),
(59, 1, '', '', '0', 'Healing Everywhere', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Healing Everywhere', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Man Health', '2024-05-23', '2024-05-22 13:03:27'),
(60, 1, '', '', '0', 'dbnapkvnk adbapkbn asvasnvpnk', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/form_basics.phphttp://localhost/RuangAdmin-master/form_basics.phphttp://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/fresh/index.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/fresh/index.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/fresh/index.php', 'dbns0ib  sdkbad b advadp advklan ', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'God ', '2024-05-14', '2024-05-22 13:05:14'),
(61, 1, '', '', 'cbpsdbn o[sdj[oaz', 'dbnapkvnk adbapkbn asvasnvpnk', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/form_basics.phphttp://localhost/RuangAdmin-master/form_basics.phphttp://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/fresh/index.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/fresh/index.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/fresh/index.php', 'dbns0ib  sdkbad b advadp advklan ', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'God ', '2024-05-14', '2024-05-22 13:05:50'),
(62, 1, '', '', 'cbpsdbn o[sdj[oaz', 'dbnapkvnk adbapkbn asvasnvpnk', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/form_basics.phphttp://localhost/RuangAdmin-master/form_basics.phphttp://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/fresh/index.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/fresh/index.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/fresh/index.php', 'dbns0ib  sdkbad b advadp advklan ', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'http://localhost/fresh/index.php', 'God ', '2024-05-14', '2024-05-22 13:07:45'),
(63, 13, 'Healthy Living Compendium Book', '', 'Healing Everywhere', 'Healing Everywhere', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Healing everywhere', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.phphttp://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Man, Men, Everywhere', '2024-05-30', '2024-05-22 13:10:30'),
(66, 13, 'Healthy Living Compendium Book', '', 'Healing Everywhere', 'Healing Everywhere', 'http://localhost/fresh/index.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Healing Everywhere', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Is Good', '2024-05-23', '2024-05-22 13:35:02'),
(67, 13, 'Healthy Living Compendium Book', 'Gengle', 'Healing To The Nations', 'Healing to the nations', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.phphttp://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'Healing to the nations', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'dbn sp adg bsdpjb', '2024-05-29', '2024-05-22 15:03:56'),
(68, 13, 'Healthy Living Compendium Book', 'MonpaTawang', 'Healing To The Nations', 'Healing to the nations', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.phphttp://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'Healing to the nations', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'http://localhost/ruangadmin/RuangAdmin-master/form_basics.php', 'dbn sp adg bsdpjb', '2024-05-29', '2024-05-22 15:05:23'),
(69, 13, 'Healthy Living Compendium Book', 'Tamajaq, Tawallammat', 'Healing Everywhere', 'Healing Everywhere', 'http://localhost/fresh/index.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/register.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Healing Everywhere', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Is Good', '2024-05-23', '2024-05-22 15:07:05'),
(70, 13, 'Healthy Living Compendium Book', 'English language', 'Healing To The Nations', 'Healing To The Nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Healing To The Nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Is Good', '2024-05-23', '2024-05-22 15:08:45');
INSERT INTO `magcontent` (`id`, `productId`, `product_category`, `language`, `content_name`, `content_description`, `content_url1`, `content_url2`, `content_url3`, `content_url4`, `content_url5`, `content_url6`, `content_url7`, `content_url8`, `content_url9`, `content_text`, `thumbnail`, `content_image`, `content_image1`, `content_image2`, `key_words`, `content_date`, `timestamp`) VALUES
(71, 13, 'Healthy Living Compendium Book', 'Yoruba (Ekiti)', 'Healing Everywhere', 'Healing To The Nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Healing To The Nations Of The World', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God, Humanity, Sandra', '2024-05-23', '2024-05-22 15:13:07'),
(72, 13, 'Healthy Living Compendium Book', 'English language', 'sb sdvsdb sdad', 'vdzs asvava asvava', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://http://localhost/RuangAdmin-master/form_basics.php/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.phphttp://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'Healing To The Nations', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'http://localhost/RuangAdmin-master/form_basics.php', 'God Hope Salvation', '2024-05-23', '2024-05-22 15:49:45');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `firstname` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `lastname` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`Id`, `firstname`, `lastname`, `email`, `password`) VALUES
(1, '', '', 'ilivieda1@yahoo.com', '$2y$10$U42HOY/JFh1Bpp9T7x8x2OwtihjPtd/9kcsnwtlQ.xvi43c9OKsx2'),
(2, '', '', 'milivieda@yahoo.com', '$2y$10$sfC7JCOOgdvzzfg5k9ppRu.nQiqlD7Jys8wDh89B93ryrZxZc8az6'),
(3, '', '', 'sendo@yahoo.com', '$2y$10$haUHRxNhRxWrRGXmx9Zf6.OYrOqNMr4ZGZE1jnZYgrQWtlDmVHsNW'),
(4, '', '', 'kunle.hsth@gmail.com', '$2y$10$/E2HwovSxxZuRMQOINaNHOAYU0NqFy9.LJ8towFnxjtS08Nxjspq.'),
(5, '', '', 'kunle.hsth@gmail.com', '$2y$10$Hyh2QHu1lwLeA2Be/rA9IeCCJu7Xb6xvxoGyf31FuwBptSU3G65cC'),
(6, '', '', 'emialeh4@gmail.com', '$2y$10$OUYHeTVOqzAuBGRNd3y1geBEq/SP1H80ROqNr5poDRR3L7AhvJCKG'),
(7, '', '', 'emialeh4@gmail.com', '$2y$10$HQCkn5NGMyuQRwlxqx56juw0wNa1bUL3zfbCwGGD8fUz8MrvHRbTy');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
